FROM node:16 as build

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

FROM nginx
RUN apt-get update
RUN apt-get install -y curl

COPY ngnix.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]