services:
  frontend:
    container_name: frontend
    build: 
      context: ./client
      dockerfile: Dockerfile.frontend
    depends_on: 
      - backend
    ports:
      - 5173:5173
    networks:
      - app_network

  backend:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile.backend
    depends_on: 
      - db
    ports:
      - 3000:3000
    networks:
      - app_network

  db:
    container_name: db
    build: 
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
 app_network:
    driver: bridge